/*
 * Copyright (C) 2017 lucidiot
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package boogle.ui;

import boogle.jeu.HighscoresManager;
import java.util.PrimitiveIterator;
import java.util.stream.IntStream;
import javax.swing.table.TableModel;

/**
 * Formulaire de menu des meilleurs scores.
 * @author lucidiot
 */
public class MasterRaceForm extends javax.swing.JFrame {

    /**
     * Creates new form MasterRaceForm
     */
    public MasterRaceForm() {
        initComponents();
    }

    @Override
    public void setVisible(boolean bln) {
        super.setVisible(bln);
        if(bln) {
            masterRaceTable.setModel(getMasterRaceModel());
            masterRaceTable.getColumnModel().getColumn(0).setMaxWidth(30);
            masterRaceTable.getColumnModel().getColumn(2).setMaxWidth(70);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        masterRaceTable = new javax.swing.JTable();

        setTitle("Meilleurs scores");

        masterRaceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(masterRaceTable);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private TableModel getMasterRaceModel() {
        return new javax.swing.table.DefaultTableModel(getMasterRaceData(), new String [] { "#", "Nom", "Score" }) {
            Class[] types = new Class[] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean[] { false, false, false };
            @Override
            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };
    }

    private Object[][] getMasterRaceData() {
        PrimitiveIterator.OfInt counter = IntStream.iterate(1, i -> i + 1).iterator();
        return HighscoresManager.getMasterRace().stream().map(p -> {
            return new Object[] {counter.nextInt(), p.getName(), p.getScore()};
        }).toArray(Object[][]::new);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable masterRaceTable;
    // End of variables declaration//GEN-END:variables
}
